device_type: mimxrt1060
job_name: basic_mcu_ota_se05x

timeouts:
  job:
    minutes: 20
  action:
    minutes: 10
  connection:
    minutes: 5
tags:
  - "nuc-worker-11"
priority: medium
visibility: public
metadata:
  CI_TEST_1/RUNNING_FROM_SLOT: "1"
  CI_TEST_1/CHECKIN: "successful"
  CI_TEST_2/RUNNING_FROM_SLOT: "2"
  CI_TEST_2/CHECKIN: "successful"
  CI_TEST_3/RUNNING_FROM_SLOT: "1"
  CI_TEST_4/ROLLBACK_TEST: "1"
  CI_TEST_3/CHECKIN: "successful"
  CI_TEST_3/ROLLBACK: "1"
actions:
- command:
    namespace: cleanup
    name: serial_down
- command:
    namespace: cleanup
    name: serial_up
- deploy:
    namespace: cleanup
    timeout:
      minutes: 15
    to: downloads
    images:
      build:
        url: https://s.lava.infra.foundries.io/el2go_cleanup_rt1060.signed.bin
        headers:
          Authorization: LAVA_BASIC_AUTH
      mcuboot:
        url: https://s.lava.infra.foundries.io/mcuboot_opensource_rt1060.elf
        headers:
          Authorization: LAVA_BASIC_AUTH
    postprocess:
      docker:
        image: ghcr.io/foundriesio/mcubuild:latest
        steps:
        - export IMAGE_PATH=$PWD
        - ls -l "${IMAGE_PATH}"
        - echo "DEVICE_TYPE=mimxrt1060" >> flash.settings
        - echo "TMPFILES=mcuboot_opensource_rt1060.elf" >> flash.settings
        - ls -l $IMAGE_PATH
- deploy:
    namespace: cleanup
    timeout:
      minutes: 5
    to: flasher
    images:
      image:
        url: downloads://el2go_cleanup_rt1060.signed.bin
      settings:
        url: downloads://flash.settings
      mcuboot:
        url: downloads://mcuboot_opensource_rt1060.elf
- boot:
    namespace: cleanup
    timeout:
      minutes: 10
    method: minimal
- test:
    namespace: cleanup
    monitors:
    - name: "basic_test"
      start: "---------STARTING DEMO---------"
      end: "Halting execution"
      pattern: _unused_

- command:
    namespace: cleanup
    name: remove_from_factory
- command:
    namespace: cleanup
    name: remove_from_denied

- deploy:
    namespace: testrun
    connection-namespace: cleanup
    timeout:
      minutes: 15
    to: downloads
    images:
      build:
        url: {BUILD_URL}
        headers:
          Authorization: GITHUB_AUTH
      mcuboot:
        url: https://s.lava.infra.foundries.io/mcuboot_opensource_rt1060.elf
        headers:
          Authorization: LAVA_BASIC_AUTH
    postprocess:
      docker:
        image: miloszwasilewski/mcu_lava:latest
        steps:
        - export IMAGE_PATH=$PWD
        - ls -l "${IMAGE_PATH}"
        - unzip "zip"
        - ls -l "${IMAGE_PATH}"
        - echo "DEVICE_TYPE=mimxrt1060" >> flash.settings
        - echo "TMPFILES=mcuboot_opensource_rt1060.elf" >> flash.settings
        - ls -l $IMAGE_PATH
- deploy:
    namespace: testrun
    connection-namespace: cleanup
    timeout:
      minutes: 7
    to: flasher
    images:
      image:
        url: downloads://ota_demo.SE05X_rt1060.{OTA_REVISION_BASE}101.signed.bin
      settings:
        url: downloads://flash.settings
      mcuboot:
        url: downloads://mcuboot_opensource_rt1060.elf
- boot:
    namespace: testrun
    connection-namespace: cleanup
    timeout:
      minutes: 10
    method: minimal
- test:
    timeout:
      minutes: 10
    namespace: testrun
    connection-namespace: cleanup
    monitors:
    - name: "boot_test"
      start: "---------STARTING DEMO---------"
      end: "REVISION=v{OTA_REVISION_BASE}103 ROLLBACK=1"
      pattern: _unused_
