device_type: mimxrt1170_cm7
job_name: basic_mcu_ota_standard
timeouts:
  job:
    minutes: 20
  action:
    minutes: 5
  connection:
    minutes: 2
tags:
  - "nuc-worker-11"
priority: medium
visibility: public
metadata:
  CI_TEST_1/RUNNING_FROM_SLOT: "1"
  CI_TEST_1/CHECKIN: "successful"
  CI_TEST_2/RUNNING_FROM_SLOT: "2"
  CI_TEST_2/CHECKIN: "successful"
  CI_TEST_3/RUNNING_FROM_SLOT: "1"
  CI_TEST_4/ROLLBACK_TEST: "1"
  CI_TEST_3/CHECKIN: "successful"
  CI_TEST_3/ROLLBACK: "1"
actions:
- deploy:
    timeout:
      minutes: 15
    to: downloads
    images:
      build:
        url: {BUILD_URL}
        headers:
          Authorization: GITHUB_AUTH
      mcuboot:
        url: https://s.lava.infra.foundries.io/mcuboot_opensource_rt1170.elf
        headers:
          Authorization: LAVA_BASIC_AUTH
    postprocess:
      docker:
        image: ghcr.io/foundriesio/mcubuild:latest
        steps:
        - export IMAGE_PATH=$PWD
        - ls -l "${IMAGE_PATH}"
        - unzip "zip"
        - ls -l "${IMAGE_PATH}"
        - echo "DEVICE_TYPE=mimxrt1170_cm7" >> flash.settings
        - echo "TMPFILES=mcuboot_opensource_rt1170.elf" >> flash.settings
        - ls -l $IMAGE_PATH
- deploy:
    timeout:
      minutes: 5
    to: flasher
    images:
      image:
        url: downloads://ota_demo.rt1170.{OTA_REVISION_BASE}001.signed.bin
      settings:
        url: downloads://flash.settings
      mcuboot:
        url: downloads://mcuboot_opensource_rt1170.elf
- command:
    name: remove_from_factory
- command:
    name: remove_from_denied
- boot:
    timeout:
      minutes: 10
    method: minimal
- test:
    timeout:
      minutes: 10
    monitors:
    - name: "basic_test"
      start: "---------STARTING DEMO---------"
      end: "REVISION=v{OTA_REVISION_BASE}003 ROLLBACK=1"
      pattern: _unused_
